// GENERATED by bin/luhtech-sync-venture-directory.mjs -- DO NOT HAND-EDIT.
// Regenerate with `luhtech-sync-venture-directory` (reads each venture's own
// content/brand/{id}.json identity.name / identity.oneLiner from its
// sibling repo checkout on disk). A venture with no entry here falls back
// to its raw brandRef slug in VentureCard.astro.
export interface VentureDirectoryEntry {
	name: string;
	oneLiner: string;
}

export const VENTURE_DIRECTORY: Record<string, VentureDirectoryEntry> = {
  ectropy: {"name":"Ectropy","oneLiner":"The construction intelligence platform that binds each decision to its place, its cost, and its people."},
  qullqa: {"name":"Qullqa","oneLiner":"A complete platform for designing and building homes, from feasibility to completion. Beginning with the ADU."},
  siltana: {"name":"Siltana","oneLiner":"Building intelligence from design through occupancy and fifty years of operation."},
  jobsitecontrol: {"name":"JobsiteControl","oneLiner":"Edge computing and connectivity built for the jobsite, wherever it is."},
  viiva: {"name":"Viiva","oneLiner":"Design intent routed to fabrication. Beginning with MEP."},
  ohjaus: {"name":"Ohjaus","oneLiner":"Open-standard sensor infrastructure for embedded applications."},
  raizal: {"name":"Raizal","oneLiner":"A cooperative carbon marketplace with credits traced to the field."},
  replique: {"name":"Replique","oneLiner":"Protocol intelligence for the research bench."},
  hilja: {"name":"Hilja","oneLiner":"Intelligent surfaces that tune a room to how it's being used."},
};
